#!/usr/bin/env python3
"""Builds the static pages of nexper.in and checks the translations.

All visible text lives in i18n/<lang>.json. English (i18n/en.json) is the
source; the pages are generated with English text plus data-i18n keys, and
assets/i18n.js swaps in the visitor's language in the browser.

    python3 tools/build.py           # regenerate the HTML pages
    python3 tools/build.py --check   # fail if pages or translations are out of date (CI runs this)
    python3 tools/build.py --stamp   # after updating every language, record that they match English

Never edit the generated .html files by hand: change this file or the JSON.
"""

import hashlib
import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
I18N = os.path.join(ROOT, "i18n")
APP = "https://app.nexper.in"
SITE = "https://nexper.in"

# Fill these in to show the contact cards. WhatsApp: digits with country code, e.g. 919876543210
SUPPORT_EMAIL = "maqbooln2022@gmail.com"
SUPPORT_WHATSAPP = "919108169321"

GENERATED_NOTE = "<!-- Generated by tools/build.py. Do not edit by hand; see CLAUDE.md. -->"


def load_json(name):
    with open(os.path.join(I18N, name), encoding="utf-8") as f:
        return json.load(f)


LANGS = load_json("languages.json")
EN = load_json("en.json")
USED = set()


def t(key):
    """English text for a key. Records the key so unused keys can be reported."""
    if key not in EN:
        raise SystemExit(f"Missing key in i18n/en.json: {key}")
    USED.add(key)
    return EN[key]


def tag(name, key, cls=None, extra=""):
    """<name data-i18n="key">English</name>"""
    c = f' class="{cls}"' if cls else ""
    return f'<{name}{c} data-i18n="{key}"{extra}>{t(key)}</{name}>'


def asset_version():
    h = hashlib.sha1()
    for rel in ("assets/site.css", "assets/site.js", "assets/i18n.js", "assets/icons.svg"):
        with open(os.path.join(ROOT, rel), "rb") as f:
            h.update(f.read())
    for lang in LANGS:
        p = os.path.join(I18N, f"{lang['code']}.json")
        if os.path.exists(p):
            with open(p, "rb") as f:
                h.update(f.read())
    return h.hexdigest()[:8]


V = asset_version()


def ico(name, cls="ico"):
    return f'<svg class="{cls}" aria-hidden="true"><use href="/assets/icons.svg?v={V}#{name}"/></svg>'


# ---------------------------------------------------------------- layout


def head(title_key, desc_key, path, raw=None):
    """Page <head>. raw=(title, description) for English-only pages."""
    codes = [l["code"] for l in LANGS]
    if raw:
        title, desc = (html.escape(x, quote=True) for x in raw)
        title_attr = desc_attr = ""
    else:
        title = html.escape(t(title_key), quote=True)
        desc = html.escape(t(desc_key), quote=True)
        title_attr = f' data-i18n="{title_key}"'
        desc_attr = f' data-i18n-attr="content:{desc_key}"'

    return f"""<!doctype html>
<html lang="en-IN">
{GENERATED_NOTE}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title{title_attr}>{title}</title>
<meta name="description" content="{desc}"{desc_attr}>
<link rel="canonical" href="{SITE}{path}">
<meta name="theme-color" content="#08070f">
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Nexper">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="{SITE}{path}">
<meta property="og:image" content="{SITE}/og.jpg">
<meta property="og:locale" content="en_IN">
<meta name="twitter:card" content="summary_large_image">
<script>
  // Hide the page briefly while a saved non-English language loads, so
  // visitors don't see English flash first. assets/i18n.js clears this.
  (function () {{
    var codes = {json.dumps(codes[1:])};
    var l = null;
    try {{ l = new URLSearchParams(location.search).get("lang") || localStorage.getItem("nexper.lang"); }} catch (e) {{}}
    if (!l && navigator.languages) {{
      for (var i = 0; i < navigator.languages.length && !l; i++) {{
        var c = navigator.languages[i].slice(0, 2).toLowerCase();
        if (c === "en" || codes.indexOf(c) > -1) l = c;
      }}
    }}
    if (l && codes.indexOf(l) > -1) {{
      var d = document.documentElement;
      d.setAttribute("data-lang-pending", "");
      setTimeout(function () {{ d.removeAttribute("data-lang-pending"); }}, 2500);
    }}
  }})();
</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&family=Manrope:wght@700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/site.css?v={V}">
</head>
<body>
<a class="skip" href="#main" data-i18n="skip">{t("skip")}</a>
"""


NAV = [("/#features", "nav.features"), ("/#how", "nav.how"), ("/#pricing", "nav.pricing"), ("/faq/", "nav.faq")]


def lang_picker():
    """Language dropdown. assets/i18n.js reads the options from here."""
    items = ""
    for l in LANGS:
        font = f' data-font="{l["font"]}"' if l.get("font") else ""
        sub = f'<span class="lang-en">{l["english"]}</span>' if l["code"] != "en" else ""
        items += (
            f'<li><button type="button" role="menuitemradio" aria-checked="false" data-lang-option="{l["code"]}"'
            f' data-html-lang="{l["htmlLang"]}"{font} lang="{l["htmlLang"]}">'
            f'<span class="lang-native">{l["name"]}</span>{sub}{ico("check", "ico lang-tick")}</button></li>'
        )
    first = LANGS[0]["name"]
    return f"""<div class="lang-menu" data-lang-menu>
        <button type="button" class="lang-btn" aria-haspopup="true" aria-expanded="false" aria-label="{t("nav.language")}" data-i18n-attr="aria-label:nav.language">{ico("globe")}<span data-lang-current>{first}</span>{ico("chevron-down", "ico lang-chevron")}</button>
        <ul class="lang-list" role="menu" hidden>{items}</ul>
      </div>"""


def header():
    nav = "".join(tag("a", k, extra=f' href="{h}"') for h, k in NAV)
    mob = nav + tag("a", "nav.signin", extra=f' href="{APP}/login"')
    return f"""<header class="header">
  <div class="wrap header-inner">
    <a class="wordmark" href="/" aria-label="Nexper home">Ne<span>x</span>per</a>
    <nav class="nav" aria-label="Main">{nav}</nav>
    <div class="header-actions">
      {lang_picker()}
      {tag("a", "nav.signin", "signin", f' href="{APP}/login"')}
      {tag("a", "nav.start", "btn btn-dark header-start", f' href="{APP}/login?mode=signup"')}
      <button class="menu-btn" type="button" aria-label="{t("nav.menu")}" data-i18n-attr="aria-label:nav.menu" aria-expanded="false" aria-controls="mobile-menu">{ico("menu")}</button>
    </div>
  </div>
  <nav class="mobile-menu" id="mobile-menu" aria-label="Mobile">{mob}</nav>
</header>
"""


def footer():
    cols = [
        ("footer.product", NAV),
        ("footer.company", [("/contact/", "footer.contact"), ("/privacy/", "footer.privacy"), ("/terms/", "footer.terms")]),
        ("footer.account", [(f"{APP}/login", "nav.signin"), (f"{APP}/login?mode=signup", "nav.start"), (f"{APP}/login?mode=staff", "footer.staff")]),
    ]
    def link(h, k):
        return "<li>" + tag("a", k, extra=f' href="{h}"') + "</li>"

    c = "".join(f"<div>{tag('h4', title)}<ul>" + "".join(link(h, k) for h, k in links) + "</ul></div>" for title, links in cols)
    return f"""<footer class="footer">
  <div class="wrap">
    <div class="footer-grid">
      <div class="footer-brand">
        <a class="wordmark" href="/">Ne<span>x</span>per</a>
        {tag("p", "footer.tagline")}
      </div>
      {c}
    </div>
    <div class="footer-bottom">
      <span>&copy; <span data-year>2026</span> Nexper. {tag("span", "footer.rights")}</span>
      {tag("span", "footer.madein")}
    </div>
  </div>
</footer>
<script src="/assets/site.js?v={V}" defer></script>
<script src="/assets/i18n.js?v={V}" defer></script>
</body>
</html>
"""


# ---------------------------------------------------------------- pages


def ticks(keys):
    return '<ul class="ticks">' + "".join(f"<li>{ico('check')}{tag('span', k)}</li>" for k in keys) + "</ul>"


SHOPS = [("store", "shops.kirana"), ("cart", "shops.super"), ("wrench", "shops.auto"), ("shirt", "shops.clothing"), ("sparkles", "shops.other")]
GRID = [("chart", "gst"), ("wifi-off", "offline"), ("users", "staff"), ("calculator", "dayclose"), ("truck", "suppliers"), ("scan", "scan")]
SOON = [("camera", "photo"), ("megaphone", "offers"), ("message", "order"), ("mic", "voice")]
FAQ_COUNT = 7


def line(name, qty, amount):
    return (
        f'<div class="line"><span><b>{name}</b><i>{tag("span", "phone.qty")} {qty}</i></span>'
        f'<span class="amt">&#8377;{amount}</span></div>'
    )


def home():
    out = head("home.meta.title", "home.meta.description", "/") + header()
    out += f"""<main id="main">
<section class="hero">
  <div class="wrap hero-grid">
    <div>
      {tag("span", "home.hero.tagline", "tagline")}
      {tag("h1", "home.hero.title")}
      {tag("p", "home.hero.sub", "hero-sub")}
      <div class="hero-ctas">
        <a class="btn btn-primary btn-lg" href="{APP}/login?mode=signup">{tag("span", "nav.start")} {ico("arrow-right")}</a>
        {tag("a", "home.hero.cta2", "btn btn-ghost btn-lg", ' href="#how"')}
      </div>
      <ul class="checks">
        <li>{ico("check")}{tag("span", "home.hero.check1")}</li>
        <li>{ico("check")}{tag("span", "home.hero.check2")}</li>
        <li>{ico("check")}{tag("span", "home.hero.check3")}</li>
      </ul>
    </div>

    <div class="phone-stage" aria-hidden="true">
      <div class="phone">
        <div class="screen">
          <div class="screen-top"><small>Sharma General Store</small>{tag("strong", "phone.newbill")}</div>
          <div class="screen-body">
            {line("Aashirvaad Atta 5kg", 1, 245)}
            {line("Amul Taaza 1L", 2, 108)}
            {line("Parle-G 100g", 3, 30)}
            {line("Tata Salt 1kg", 1, 28)}
            <div class="pay">{tag("span", "phone.cash")}<span class="on">UPI</span>{tag("span", "phone.udhaar")}</div>
            <div class="total">{tag("span", "phone.total")}<span class="amt">&#8377;411</span></div>
            {tag("div", "phone.send", "screen-cta")}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="shops" aria-label="Shop types">
  <div class="wrap shops-inner">
    {tag("p", "shops.madefor")}
    {"".join(f'<span class="pill">{ico(i)}{tag("span", k)}</span>' for i, k in SHOPS)}
  </div>
</section>

<section class="section" id="features">
  <div class="wrap">
    <div class="section-head">
      {tag("span", "features.eyebrow", "eyebrow")}
      {tag("h2", "features.title")}
      {tag("p", "features.sub")}
    </div>

    <div class="rows">
      <article class="row">
        <div class="row-copy">
          {tag("span", "billing.eyebrow", "eyebrow")}
          {tag("h3", "billing.title")}
          {tag("p", "billing.text")}
          {ticks(["billing.t1", "billing.t2", "billing.t3"])}
        </div>
        <div class="demo" aria-hidden="true">
          <div class="search">{ico("search")}<span>atta</span>{ico("mic", "ico mic")}</div>
          <div class="demo-card"><div class="grow"><b>Aashirvaad Atta 5kg</b><small>{tag("span", "demo.instock")} 18</small></div><span class="amt">&#8377;245</span>{tag("span", "demo.add", "tag tag-blue")}</div>
          <div class="demo-card"><div class="grow"><b>Fortune Chakki Atta 10kg</b><small>{tag("span", "demo.instock")} 6</small></div><span class="amt">&#8377;480</span>{tag("span", "demo.add", "tag tag-blue")}</div>
          <div class="demo-card"><div class="grow"><b>Pillsbury Atta 1kg</b><small>{tag("span", "demo.instock")} 24</small></div><span class="amt">&#8377;58</span>{tag("span", "demo.add", "tag tag-blue")}</div>
        </div>
      </article>

      <article class="row">
        <div class="row-copy">
          {tag("span", "stock.eyebrow", "eyebrow")}
          {tag("h3", "stock.title")}
          {tag("p", "stock.text")}
          {ticks(["stock.t1", "stock.t2", "stock.t3"])}
        </div>
        <div class="demo" aria-hidden="true">
          <div class="demo-card"><span class="avatar" style="background:var(--red-soft);color:var(--red)">{ico("alert")}</span><div class="grow"><b>Maggi Noodles 70g</b>{tag("small", "demo.low.text")}</div>{tag("span", "demo.low.tag", "tag tag-red")}</div>
          <div class="demo-card"><span class="avatar" style="background:var(--amber-soft);color:var(--amber)">{ico("clock")}</span><div class="grow"><b>Amul Butter 100g</b>{tag("small", "demo.exp.text")}</div>{tag("span", "demo.exp.tag", "tag tag-amber")}</div>
          <div class="demo-card"><span class="avatar" style="background:var(--green-soft);color:var(--green)">{ico("sparkles")}</span><div class="grow"><b>Britannia Bread 400g</b>{tag("small", "demo.offer.text")}</div>{tag("span", "demo.offer.tag", "tag tag-green")}</div>
        </div>
      </article>

      <article class="row">
        <div class="row-copy">
          {tag("span", "udhaar.eyebrow", "eyebrow")}
          {tag("h3", "udhaar.title")}
          {tag("p", "udhaar.text")}
          {ticks(["udhaar.t1", "udhaar.t2", "udhaar.t3"])}
        </div>
        <div class="demo" aria-hidden="true">
          <div class="demo-card"><span class="avatar">RK</span><div class="grow"><b>Ravi Kumar</b>{tag("small", "demo.paid12")}</div><span class="amt" style="color:var(--amber)">&#8377;1,250</span></div>
          <div class="demo-card"><span class="avatar">MS</span><div class="grow"><b>Meena S.</b>{tag("small", "demo.paid3")}</div><span class="amt" style="color:var(--amber)">&#8377;380</span></div>
          <div class="wa-bubble">{tag("span", "demo.wa")}<small>10:42 &#10003;&#10003;</small></div>
        </div>
      </article>
    </div>

    <div class="grid">
      {"".join(f'<div class="card"><span class="icon-box">{ico(i)}</span>{tag("h3", f"grid.{k}.title")}{tag("p", f"grid.{k}.text")}</div>' for i, k in GRID)}
    </div>
  </div>
</section>

<section class="section" id="how">
  <div class="wrap">
    <div class="section-head">
      {tag("span", "how.eyebrow", "eyebrow")}
      {tag("h2", "how.title")}
      {tag("p", "how.sub")}
    </div>
    <div class="steps">
      {"".join(f'<div class="step"><span class="step-n">{n}</span>{tag("h3", f"how.s{n}.title")}{tag("p", f"how.s{n}.text")}{tag("span", f"how.s{n}.time", "tag tag-blue time")}</div>' for n in (1, 2, 3))}
    </div>
  </div>
</section>

<section class="section" id="soon">
  <div class="wrap">
    <div class="soon">
      <div class="section-head">
        {tag("span", "soon.eyebrow", "eyebrow")}
        {tag("h2", "soon.title")}
        {tag("p", "soon.sub")}
      </div>
      <div class="soon-grid">
        {"".join(f'<div class="soon-card"><span class="icon-box">{ico(i)}</span>{tag("h3", f"soon.{k}.title")}{tag("p", f"soon.{k}.text")}</div>' for i, k in SOON)}
      </div>
    </div>
  </div>
</section>

<section class="section" id="pricing">
  <div class="wrap">
    <div class="section-head">
      {tag("span", "pricing.eyebrow", "eyebrow")}
      {tag("h2", "pricing.title")}
      {tag("p", "pricing.sub")}
    </div>
    <p class="early">{ico("sparkles")}{tag("span", "pricing.early")}</p>
    <div class="plans">
      <div class="plan">
        {tag("span", "pricing.free.name", "plan-name")}
        <span class="price">&#8377;0</span>
        {tag("span", "pricing.free.note", "plan-note")}
        {ticks([f"pricing.free.f{i}" for i in range(1, 8)])}
        {tag("a", "nav.start", "btn btn-ghost", f' href="{APP}/login?mode=signup"')}
      </div>
      <div class="plan featured">
        {tag("span", "pricing.pro.badge", "plan-badge")}
        {tag("span", "pricing.pro.name", "plan-name")}
        <span class="price">&#8377;99<small> {tag("span", "pricing.pro.per")}</small></span>
        {tag("span", "pricing.pro.note", "plan-note")}
        {ticks([f"pricing.pro.f{i}" for i in range(1, 7)])}
        {tag("a", "pricing.pro.cta", "btn btn-dark", f' href="{APP}/login?mode=signup"')}
      </div>
    </div>
  </div>
</section>

<section class="closing">
  <div class="wrap">
    <div class="closing-box">
      {tag("h2", "closing.title")}
      {tag("p", "closing.sub")}
      <a class="btn btn-light btn-lg" href="{APP}/login?mode=signup">{tag("span", "nav.start")} {ico("arrow-right")}</a>
    </div>
  </div>
</section>
</main>
"""
    return out + footer()


def faq():
    items = "".join(
        f'<details><summary>{tag("span", f"faq.q{i}")}{ico("plus")}</summary>{tag("p", f"faq.a{i}")}</details>' for i in range(1, FAQ_COUNT + 1)
    )
    out = head("faq.meta.title", "faq.meta.description", "/faq/") + header()
    out += f"""<main id="main" class="page">
  {tag("h1", "faq.title")}
  {tag("p", "faq.intro", "intro")}
  <div class="faq">{items}</div>
</main>
"""
    return out + footer()


def contact():
    cards = ""
    if SUPPORT_WHATSAPP:
        cards += (
            f'<a class="contact-card" href="https://wa.me/{SUPPORT_WHATSAPP}?text=Hi%20Nexper%2C%20I%20need%20help%20with%20" target="_blank" rel="noopener">'
            f'<span class="icon-box" style="background:var(--green-soft);color:var(--wa)">{ico("message")}</span>'
            f'<span>{tag("b", "contact.wa.title")}{tag("small", "contact.wa.sub")}</span></a>'
        )
    if SUPPORT_EMAIL:
        cards += (
            f'<a class="contact-card" href="mailto:{SUPPORT_EMAIL}"><span class="icon-box">{ico("mail")}</span>'
            f'<span>{tag("b", "contact.email.title")}<small>{SUPPORT_EMAIL}</small></span></a>'
        )
    # Cards appear only once contact details are set above. Mark their keys
    # as used either way so the translations stay ready.
    for k in ("contact.wa.title", "contact.wa.sub", "contact.email.title", "contact.pending"):
        t(k)
    body = f'<div class="contact-cards">{cards}</div>' if cards else tag("p", "contact.pending", "intro", ' style="margin-top:28px"')
    out = head("contact.meta.title", "contact.meta.description", "/contact/") + header()
    out += f"""<main id="main" class="page">
  {tag("h1", "contact.title")}
  {tag("p", "contact.intro", "intro")}
  {body}
  {tag("p", "contact.seealso", extra=' style="margin-top:32px"')}
</main>
"""
    return out + footer()


def not_found():
    out = head("nf.meta.title", "nf.text", "/404") + header()
    out += f"""<main id="main" class="notfound">
  <div class="big">4<span>0</span>4</div>
  {tag("p", "nf.text")}
  {tag("a", "nf.cta", "btn btn-dark btn-lg", ' href="/"')}
</main>
"""
    return out + footer()


# Legal text stays in English (translations of legal terms need a lawyer's
# review). Header, footer and an "English only" notice are translated.
UPDATED = "1 October 2026"

LEGAL = {
    "privacy": (
        "Privacy policy",
        "What Nexper collects, why, and the choices you have.",
        "Nexper (nexper.in) is a billing, stock and udhaar app for small shops. This page explains, in plain language, what information we handle and what we do with it.",
        [
            ("What we collect", [[
                "Account details: your name, email address and password (passwords are stored hashed, never in plain text). Staff accounts use a staff code and PIN created by the shop owner.",
                "Shop data you enter: shop name and type, items, prices, stock, bills, expenses, suppliers and cash records.",
                "Customer details you choose to record, such as a name or phone number for a bill or an udhaar entry.",
                "Technical data: basic server logs, and browser storage (cookies and local storage) used to keep you signed in, to save bills on your device while you are offline, and to remember your language.",
            ]]),
            ("How we use it", [[
                "To run the service for you: sign-in, billing, stock, reports and staff permissions.",
                "To keep the service secure, prevent abuse and fix problems.",
                "To answer your support requests.",
            ], "We do not sell your data and we do not show advertising. We do not currently use advertising or analytics trackers."]),
            ("Your customers&rsquo; information", ["You decide which customer details to record, and you are responsible for having the right to record them. We process that information only to provide Nexper to you, and it is visible only to the people in your shop that you allow."]),
            ("Who helps us run Nexper", ["We use trusted service providers to operate the app. They process data on our behalf:", [
                "Supabase, for the database and sign-in.",
                "Vercel, for hosting the website and app.",
                "An AI service (Anthropic), only when you choose to scan a supplier bill. The photo you upload is sent to read the items on it.",
            ], "We share information beyond this only if the law requires it."]),
            ("Who can see your shop&rsquo;s data", ["Each shop&rsquo;s data is separated from other shops by access rules in the database. You and the staff you add can see it, limited by the permissions you set. Nexper administrators can access account and shop information when needed to operate, secure and support the service."]),
            ("Security", ["The site is served over HTTPS and access is controlled on the server. No system is perfectly secure, so please use a strong password, keep staff PINs private and sign out on shared devices."]),
            ("Keeping and deleting data", ["We keep your data while your account is active. To have your account and shop data deleted, or to correct or get a copy of it, contact us. We may keep limited records where the law requires."]),
            ("Age", ["Nexper is for business use by adults. It is not meant for children under 18."]),
            ("Changes and contact", ['If we change this policy we will update the date above. Questions or requests? See our <a href="/contact/">contact page</a>.']),
        ],
    ),
    "terms": (
        "Terms of use",
        "The rules for using Nexper.",
        "By creating an account or using Nexper (nexper.in) you agree to these terms. Please read them; they are short.",
        [
            ("Using Nexper", [[
                "You must be an adult able to enter a contract, using Nexper for a lawful business.",
                "Give accurate details and keep your password and staff PINs safe. You are responsible for activity under your account and your staff&rsquo;s accounts.",
                "Do not misuse the service: no attempts to break, overload or reverse-engineer it, and no access to other shops&rsquo; data.",
            ]]),
            ("Your data", ['The shop data you enter stays yours. You allow us to store and process it to run the service, as described in our <a href="/privacy/">privacy policy</a>. You are responsible for the accuracy of your bills, stock and tax records.']),
            ("Plans and payment", ["Nexper has a free plan and a paid Pro plan. Features, limits and prices are shown in our pricing section and may change. Where we offer features for free during early access, we may start charging for them with advance notice. Paid plans, when available, are billed through a payment partner."]),
            ("Reports and GST", ["GST summaries and exports are a convenience built from the information you enter. They are not tax advice or a filing service. Please verify your returns with a qualified accountant."]),
            ("Availability", ["We work to keep Nexper running, but it is provided as is, without a guarantee that it will always be available or error free. Keep your own records where they matter to you."]),
            ("Liability", ["To the extent the law allows, Nexper is not liable for indirect or consequential losses, such as lost profit or business interruption, and our total liability for any claim is limited to the amount you paid us in the 12 months before it."]),
            ("Ending your use", ["You can stop using Nexper at any time and ask us to delete your account. We may suspend or end accounts that break these terms or put the service or other users at risk."]),
            ("Changes, law and contact", ['We may update these terms and will change the date above when we do. Continuing to use Nexper after a change means you accept it. These terms are governed by the laws of India. Questions? See our <a href="/contact/">contact page</a>.']),
        ],
    ),
}


def legal(slug):
    title, desc, intro, sections = LEGAL[slug]
    body = ""
    for h, parts in sections:
        body += f"<h2>{h}</h2>"
        for p in parts:
            body += ("<ul>" + "".join(f"<li>{i}</li>" for i in p) + "</ul>") if isinstance(p, list) else f"<p>{p}</p>"
    page = head(None, None, f"/{slug}/", raw=(f"{title} | Nexper", desc)) + header()
    page += f"""<main id="main" class="page" lang="en">
  {tag("p", "legal.englishOnly", "lang-note")}
  <h1>{title}</h1>
  <p class="updated">Last updated {UPDATED}</p>
  <p class="intro">{intro}</p>
  {body}
</main>
"""
    return page + footer()


PAGES = {
    "index.html": home,
    "faq/index.html": faq,
    "contact/index.html": contact,
    "404.html": not_found,
    "privacy/index.html": lambda: legal("privacy"),
    "terms/index.html": lambda: legal("terms"),
}

# ---------------------------------------------------------------- checks

TAG_RE = re.compile(r"<\s*(/?)\s*([a-zA-Z0-9]+)[^>]*>")
HREF_RE = re.compile(r'href="([^"]*)"')
STAMP_FILE = os.path.join(I18N, "_source-hashes.json")


def markup_signature(s):
    return sorted(m.group(1) + m.group(2).lower() for m in TAG_RE.finditer(s)), sorted(HREF_RE.findall(s))


def en_hash(s):
    return hashlib.sha1(s.encode("utf-8")).hexdigest()[:10]


def check_translations():
    errors = []
    en_keys = set(EN)
    unused = en_keys - USED
    for k in sorted(unused):
        errors.append(f"en.json: key '{k}' is not used by any page (remove it, or use it in tools/build.py)")
    stamps = load_json("_source-hashes.json") if os.path.exists(STAMP_FILE) else {}
    for lang in LANGS[1:]:
        code = lang["code"]
        path = os.path.join(I18N, f"{code}.json")
        if not os.path.exists(path):
            errors.append(f"{code}.json is missing")
            continue
        data = load_json(f"{code}.json")
        for k in sorted(en_keys - set(data)):
            errors.append(f"{code}.json: missing translation for '{k}'")
        for k in sorted(set(data) - en_keys):
            errors.append(f"{code}.json: '{k}' is not in en.json (remove it)")
        for k in sorted(en_keys & set(data)):
            if not str(data[k]).strip():
                errors.append(f"{code}.json: '{k}' is empty")
            elif markup_signature(data[k]) != markup_signature(EN[k]):
                errors.append(f"{code}.json: '{k}' must keep the same HTML tags and links as English")
    for k in sorted(en_keys):
        if stamps.get(k) != en_hash(EN[k]):
            errors.append(
                f"'{k}' is new or its English text changed since the translations were last confirmed. "
                "Update it in every language, then run: python3 tools/build.py --stamp"
            )
    return errors


def render_all():
    USED.clear()
    return {rel: fn() for rel, fn in PAGES.items()}


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "build"
    pages = render_all()
    if mode == "--stamp":
        errors = [e for e in check_translations() if "--stamp" not in e]
        if errors:
            print("Fix these before stamping:\n  " + "\n  ".join(errors))
            sys.exit(1)
        with open(STAMP_FILE, "w", encoding="utf-8") as f:
            json.dump({k: en_hash(v) for k, v in sorted(EN.items())}, f, indent=2, ensure_ascii=False)
            f.write("\n")
        print(f"Stamped {len(EN)} keys as translated in all languages.")
        return
    if mode == "--check":
        errors = check_translations()
        for rel, content in pages.items():
            p = os.path.join(ROOT, rel)
            if not os.path.exists(p) or open(p, encoding="utf-8").read() != content:
                errors.append(f"{rel} is out of date: run python3 tools/build.py and commit the result")
        if errors:
            print(f"{len(errors)} problem(s):\n  " + "\n  ".join(errors))
            sys.exit(1)
        print(f"OK: {len(pages)} pages up to date, {len(EN)} keys translated into {len(LANGS) - 1} languages.")
        return
    for rel, content in pages.items():
        p = os.path.join(ROOT, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w", encoding="utf-8") as f:
            f.write(content)
    problems = check_translations()
    print(f"Built {len(pages)} pages (asset version {V}).")
    if problems:
        print(f"Translation check: {len(problems)} problem(s). Run --check for the list.")


if __name__ == "__main__":
    main()
